runtime:
  docker:
    image: pytorch/pytorch:2.2.0-cuda12.1-cudnn8-runtime
    gpu: false  # PPO on CartPole is fast on CPU
  resources:
    cpus: "4"
    memory: "8GB"
    has_gpu: false

dependencies:
  pip:
    - gymnasium
    - numpy

