name: verl-agent
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aom=3.6.1=h59595ed_0
  - av=10.0.0=py312h0526a69_4
  - aws-c-auth=0.9.1=h48c9088_3
  - aws-c-cal=0.9.2=he7b75e1_1
  - aws-c-common=0.12.4=hb03c661_0
  - aws-c-compression=0.3.1=h92c474e_6
  - aws-c-event-stream=0.5.6=h82d11aa_3
  - aws-c-http=0.10.4=h94feff3_3
  - aws-c-io=0.22.0=h57f3b0d_1
  - aws-c-mqtt=0.13.3=h2b1cf8c_6
  - aws-c-s3=0.8.6=h4e5ac4b_5
  - aws-c-sdkutils=0.2.4=h92c474e_1
  - aws-checksums=0.2.7=h92c474e_2
  - aws-crt-cpp=0.34.4=h60c762c_0
  - aws-sdk-cpp=1.11.606=h32384e2_4
  - azure-core-cpp=1.16.0=h3a458e0_1
  - azure-identity-cpp=1.12.0=ha729027_0
  - azure-storage-blobs-cpp=12.14.0=hb1c9500_1
  - azure-storage-common-cpp=12.10.0=hebae86a_2
  - azure-storage-files-datalake-cpp=12.12.0=h8b27e44_3
  - brotli-python=1.1.0=py312h1289d80_4
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=2.0.0=py312h35888ee_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - dav1d=1.2.1=hd590300_0
  - ffmpeg=6.0.1=gpl_h334edf3_100
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.16=hb03c661_0
  - gflags=2.2.2=h5888daf_1005
  - glog=0.7.1=hbabe93e_0
  - gmp=6.3.0=hac33072_2
  - gnutls=3.7.9=hb077bed_0
  - graphite2=1.3.14=hecca717_2
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.1.0=h15599e2_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.11=pyhd8ed1ab_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=ha97dd6f_2
  - lerc=4.0.0=h0aef613_1
  - libabseil=20250512.1=cxx17_hba17884_0
  - libarrow=21.0.0=h56a6dad_8_cpu
  - libarrow-acero=21.0.0=h635bf11_8_cpu
  - libarrow-compute=21.0.0=h8c2c5c3_8_cpu
  - libarrow-dataset=21.0.0=h635bf11_8_cpu
  - libarrow-substrait=21.0.0=h3f74fd7_8_cpu
  - libass=0.17.1=h39113c1_2
  - libblas=3.9.0=37_h4a7cf45_openblas
  - libbrotlicommon=1.1.0=hb03c661_4
  - libbrotlidec=1.1.0=hb03c661_4
  - libbrotlienc=1.1.0=hb03c661_4
  - libcblas=3.9.0=37_h0358290_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcurl=8.14.1=h332b0f4_0
  - libdeflate=1.24=h86f0d12_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.86.0=h1fed272_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=h767d61c_7
  - libgoogle-cloud=2.39.0=hdb79228_0
  - libgoogle-cloud-storage=2.39.0=hdbdcf42_0
  - libgrpc=1.73.1=h1e535eb_0
  - libiconv=1.18=h3b78370_2
  - libidn2=2.3.8=hfac485b_1
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=37_h47877c9_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_2
  - libopentelemetry-cpp=1.21.0=hb9b0907_1
  - libopentelemetry-cpp-headers=1.21.0=ha770c72_1
  - libopus=1.5.2=hd0c01bc_0
  - libparquet=21.0.0=h790f06f_8_cpu
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h421ea60_1
  - libprotobuf=6.31.1=h49aed37_2
  - libre2-11=2025.08.12=h7b12aa8_1
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libtasn1=4.20.0=hb03c661_1
  - libthrift=0.22.0=h454ac66_1
  - libtiff=4.7.1=h8261f1e_0
  - libunistring=0.9.10=h7f98852_0
  - libutf8proc=2.11.0=hb04c3b8_0
  - libuuid=2.41.2=he9a06e4_0
  - libva=2.22.0=h4f16b4b_2
  - libvpx=1.13.1=h59595ed_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxml2=2.13.8=h04c0eec_1
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.10.0=h5888daf_1
  - ncurses=6.5=h2d0b736_3
  - nettle=3.9.1=h7ab15ed_0
  - nlohmann_json=3.12.0=h54a6638_1
  - openh264=2.3.1=hcb278e6_2
  - openjpeg=2.5.4=h55fea9a_0
  - openssl=3.5.4=h26f9b46_0
  - orc=2.2.1=hd747db4_0
  - p11-kit=0.24.1=hc5aa10d_0
  - pcre2=10.46=h1321c63_0
  - pillow=11.3.0=py312h7b42cdd_3
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - prometheus-cpp=1.3.0=ha5d0236_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pyarrow=21.0.0=py312h7900ff3_1
  - pyarrow-core=21.0.0=py312hc195796_1_cpu
  - pycparser=2.22=pyh29332c3_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.12.0=hab00c5b_0_cpython
  - python_abi=3.12=8_cp312
  - re2=2025.08.12=h5301d42_1
  - readline=8.2=h8c095d6_2
  - regex=2025.9.18=py312h4c3975b_0
  - requests=2.32.5=pyhd8ed1ab_0
  - s2n=1.5.26=h5ac9029_0
  - setuptools=80.9.0=pyhff2d567_0
  - snappy=1.2.2=h03e3b7b_0
  - svt-av1=1.7.0=h59595ed_0
  - tiktoken=0.7.0=py312h26f7dfd_0
  - tk=8.6.13=noxft_hd72426e_102
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wayland=1.24.0=h3e06ad9_0
  - wayland-protocols=1.45=hd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.25.0=py312h5253ce2_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - accelerate==1.10.1
      - aiofiles==25.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.1
      - aiohttp-cors==0.8.1
      - aiosignal==1.4.0
      - aiosqlite==0.22.1
      - airportsdata==20250909
      - alembic==1.18.3
      - alfworld==0.4.2
      - annotated-types==0.7.0
      - anthropic==0.77.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - astor==0.8.1
      - asyncpg==0.31.0
      - attrs==25.4.0
      - bcrypt==4.0.1
      - blake3==1.0.8
      - blessed==1.22.0
      - blis==1.3.0
      - bracex==2.6
      - cachetools==6.2.1
      - casbin==1.43.0
      - catalogue==2.0.10
      - click==8.1.8
      - cloudpathlib==0.23.0
      - cloudpickle==3.1.1
      - cmake==4.1.0
      - codetiming==1.4.0
      - colorama==0.4.6
      - colorful==0.5.7
      - colorlog==6.10.1
      - compressed-tensors==0.9.3
      - confection==0.1.5
      - contourpy==1.3.3
      - cryptography==46.0.4
      - cupy-cuda12x==13.6.0
      - cycler==0.12.1
      - cymem==2.0.11
      - datasets==4.5.0
      - debugpy==1.8.17
      - decord==0.6.0
      - deprecated==1.2.18
      - depyf==0.18.0
      - dill==0.4.0
      - diskcache==5.6.3
      - distlib==0.4.0
      - distro==1.9.0
      - dnspython==2.8.0
      - docstring-parser==0.17.0
      - einops==0.8.1
      - email-validator==2.3.0
      - farama-notifications==0.0.4
      - fast-downward-textworld==20.6.3
      - fastapi==0.119.0
      - fastapi-cli==0.0.13
      - fastapi-cloud-cli==0.3.1
      - fastrlock==0.8.3
      - filelock==3.19.1
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - gguf==0.17.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.26.0
      - google-api-python-client==2.188.0
      - google-auth==2.48.0
      - google-auth-httplib2==0.3.0
      - google-genai==1.61.0
      - google-generativeai==0.8.6
      - googleapis-common-protos==1.70.0
      - gpustat==1.1.1
      - greenlet==3.3.1
      - grpcio==1.75.1
      - grpcio-status==1.71.2
      - gymnasium==0.29.1
      - h11==0.16.0
      - hashids==1.3.1
      - hf-xet==1.1.10
      - httpcore==1.0.9
      - httplib2==0.31.2
      - httptools==0.7.1
      - httpx==0.28.1
      - huggingface-hub==0.35.3
      - hydra-core==1.3.2
      - ijson==3.4.0.post0
      - importlib-metadata==8.0.0
      - interegular==0.3.3
      - jericho==3.3.0
      - jinja2==3.1.6
      - jiter==0.11.1
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - langcodes==3.5.0
      - language-data==1.3.0
      - lark==1.2.2
      - llguidance==0.7.30
      - llvmlite==0.44.0
      - lm-format-enforcer==0.10.12
      - mako==1.3.10
      - marisa-trie==1.3.1
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.7
      - mdurl==0.1.2
      - mementos==1.3.1
      - mistral-common==1.8.5
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - msgpack==1.1.2
      - msgspec==0.19.0
      - multidict==6.7.0
      - multiprocess==0.70.16
      - murmurhash==1.0.13
      - nest-asyncio==1.6.0
      - networkx==3.5
      - ninja==1.13.0
      - numba==0.61.2
      - numpy==2.3.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - openai==2.16.0
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - opencv-python-headless==4.12.0.88
      - opentelemetry-api==1.26.0
      - opentelemetry-exporter-otlp==1.26.0
      - opentelemetry-exporter-otlp-proto-common==1.26.0
      - opentelemetry-exporter-otlp-proto-grpc==1.26.0
      - opentelemetry-exporter-otlp-proto-http==1.26.0
      - opentelemetry-exporter-prometheus==0.59b0
      - opentelemetry-proto==1.26.0
      - opentelemetry-sdk==1.26.0
      - opentelemetry-semantic-conventions==0.47b0
      - opentelemetry-semantic-conventions-ai==0.4.13
      - orjson==3.11.3
      - outlines==0.1.11
      - outlines-core==0.1.26
      - packaging==25.0
      - pandas==2.3.3
      - partial-json-parser==0.2.1.1.post6
      - passlib==1.7.4
      - peft==0.17.1
      - pendulum==3.2.0
      - platformdirs==4.5.0
      - preshed==3.0.10
      - prettytable==3.17.0
      - prometheus-client==0.23.1
      - prometheus-fastapi-instrumentator==7.1.0
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - proto-plus==1.26.1
      - protobuf==5.29.5
      - psutil==7.1.0
      - psycopg2-binary==2.9.11
      - pulp==3.3.0
      - py-cpuinfo==9.0.0
      - py-spy==0.4.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybind11==3.0.1
      - pycasbin==2.7.1
      - pycountry==24.6.1
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pydantic-extra-types==2.10.6
      - pygments==2.19.2
      - pyjwt==2.11.0
      - pylatexenc==2.10
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - python-json-logger==4.0.0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - qwen-vl-utils==0.0.14
      - ray==2.49.2
      - referencing==0.37.0
      - rich==14.2.0
      - rich-toolkit==0.15.1
      - rignore==0.7.1
      - rpds-py==0.27.1
      - rsa==4.9.1
      - safetensors==0.6.2
      - scipy==1.16.2
      - sentencepiece==0.2.1
      - sentry-sdk==2.42.0
      - setproctitle==1.3.7
      - shellingham==1.5.4
      - simpleeval==1.0.3
      - six==1.17.0
      - skypilot==0.11.1
      - smart-open==7.3.1
      - smmap==5.0.2
      - sniffio==1.3.1
      - spacy==3.8.7
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - sqlalchemy==2.0.46
      - sqlalchemy-adapter==1.9.0
      - srsly==2.5.1
      - stable-baselines3==2.6.0
      - starlette==0.48.0
      - sympy==1.13.1
      - tabulate==0.9.0
      - tatsu==5.8.3
      - tenacity==9.1.2
      - tensordict==0.6.2
      - termcolor==3.1.0
      - textworld==1.6.2
      - thinc==8.3.6
      - tokenizers==0.21.4
      - tqdm==4.67.1
      - transformers==4.51.1
      - triton==3.2.0
      - typer==0.19.2
      - types-paramiko==4.0.0.20250822
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - uritemplate==4.2.0
      - uvicorn==0.35.0
      - uvloop==0.22.1
      - virtualenv==20.35.3
      - vllm==0.8.5
      - wandb==0.22.2
      - wasabi==1.1.3
      - watchfiles==1.1.1
      - wcmatch==10.1
      - wcwidth==0.2.14
      - weasel==0.4.1
      - websockets==15.0.1
      - wrapt==1.17.3
      - xformers==0.0.29.post2
      - xgrammar==0.1.18
      - xxhash==3.6.0
      - yarl==1.22.0
      - zipp==3.23.0
